project:
  type: website

website:
  title: "ALB"
  site-url: "https://AneLivB.github.io/ALB/"
  navbar:
    left:
      - href: ALB.qmd
        text: Home
      - href: Projects.qmd
        text: Projects        
      - href: Publications.qmd
        text: Publications   
      - href: Illustrations.qmd
        text: Illustrations   
format:
  html:
    css: styles.css
    metadata:
      name: viewport
      content: width=device-width, initial-scale=1
    toc: true

editor: visual

